use quote::quote;
use syn::{DeriveInput, parse_macro_input, Type, Token, parse_quote, Item, ItemStruct};
use syn::parse::Parse;


pub struct MacroArgsEnvState{
    scheme_type: Type,
    seed_type: Type,
}



impl Parse for MacroArgsEnvState {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut scheme_type = None;
        let mut seed_type = None;


        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let ty: Type = input.parse()?;

            match key.to_string().as_str() {

                "scheme" => scheme_type = Some(ty),
                "seed_type" => seed_type = Some(ty),
                _ => return Err(syn::Error::new(key.span(), "unknown argument")),
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(MacroArgsEnvState {
            scheme_type: scheme_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing scheme")
            })?,
            seed_type: seed_type.unwrap_or_else(|| syn::parse_quote!(())),
        })
    }
}


pub struct MacroArgsImplMcp{
    target_type: Type,
    scheme_type: Type,
    seed_type: Type,
}
impl Parse for MacroArgsImplMcp {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut scheme_type = None;
        let mut seed_type = None;
        let mut target_type = None;

        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let ty: Type = input.parse()?;

            match key.to_string().as_str() {
                "target" => target_type = Some(ty),
                "scheme" => scheme_type = Some(ty),
                "seed_type" => seed_type = Some(ty),
                _ => return Err(syn::Error::new(key.span(), "unknown argument")),
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(MacroArgsImplMcp {
            scheme_type: scheme_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing scheme")
            })?,
            seed_type: seed_type.unwrap_or_else(|| syn::parse_quote!(())),
            target_type: target_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing target")
            })?,

        })
    }
}

pub fn impl_mcp_env_state(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream{


    let item_copy = item.clone();
    let ast = parse_macro_input!(item_copy as DeriveInput);
    //let scheme = parse_macro_input!(attr as syn::Ident);
    let args = syn::parse_macro_input!(attr as MacroArgsEnvState);
    let scheme = args.scheme_type;
    let seed_type = args.seed_type;
    let implementation = {

        let ident = ast.ident.clone();

        let mcp_struct_name = syn::Ident::new(&format!("Mcp{}", ident), proc_macro2::Span::call_site());

        quote!{
            /// Generated by `mcp_env_state` macro.
            #[derive(Clone)]
            pub struct #mcp_struct_name {
                core: amfiteatr_core::env::McpCoreSequentialEnvironment<#scheme, #ident, ()>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#mcp_struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#mcp_struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }

            impl #mcp_struct_name{
                /// Creates new instance of structure
                pub fn mcp_new(initial_state: #ident) -> Self{
                    Self{
                        core: amfiteatr_core::env::McpCoreSequentialEnvironment::new(
                            initial_state
                        ),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router()
                    }
                }
            }

            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_router]
            impl #mcp_struct_name{

                fn _create_resource_text(&self, uri: &str, name: &str) -> rmcp::model::Resource {
                    rmcp::model::RawResource::new(uri, name.to_string()).no_annotation()
                }

                /// Generated by `mcp_env_state` macro.
                #[rmcp::tool(description = "Reset environment - set game in initial state")]
                async fn reset(&self) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {
                    self.core.reset(rmcp::handler::server::wrapper::Parameters(#seed_type)).await
                }

                #[rmcp::tool(description = "Get updates for selected agent")]
                async fn get_updates(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {

                    self.core.get_updates(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await

                }

                #[rmcp::tool(description = "Get score of specific agent")]
                async fn get_score(
                    &self,
                   rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                )  -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{

                    self.core.get_score(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await
                }

                #[rmcp::tool(description = "Process action on environment and produce update messages")]
                async fn process_action(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentAction<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    self.core.process_action(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action})).await

                }

            }

            #[rmcp::prompt_router]
            impl #mcp_struct_name{
                #[rmcp::prompt(
                    name = "player_step_prompt",
                    meta = Meta(rmcp::object!({"meta_key": "meta_value"}))
                )]
                async fn player_step_prompt(
                    &self,
                    _ctx: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) ->  Result<rmcp::model::GetPromptResult, rmcp::ErrorData> {
                    self.core.player_step_prompt(_ctx).await
                }





            }


            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_handler(meta = Meta(rmcp::object!({"tool_meta_key": "tool_meta_value"})))]
            #[rmcp::prompt_handler(meta = Meta(rmcp::object!({"router_meta_key": "router_meta_value"})))]
            #[rmcp::task_handler]
            impl rmcp::ServerHandler for #mcp_struct_name{
                fn get_info(&self) -> rmcp::model::ServerInfo {

                    rmcp::model::ServerInfo::new(
                        rmcp::model::ServerCapabilities::builder()
                            .enable_tools()
                            .enable_prompts()
                            .enable_tasks()
                            .build()
                    )
                        .with_server_info(rmcp::model::Implementation::from_build_env())
                        .with_protocol_version(rmcp::model::ProtocolVersion::V_2024_11_05)
                        .with_instructions(format!("A game environment for game {} (controls game flow)", self.core.game_name()))
                }

                async fn initialize(
                    &self,
                    _request: rmcp::model::InitializeRequestParams,
                    context: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) -> Result<rmcp::model::InitializeResult, rmcp::ErrorData> {
                    if let Some(http_request_part) = context.extensions.get::<axum::http::request::Parts>() {
                        let initialize_headers = &http_request_part.headers;
                        let initialize_uri = &http_request_part.uri;
                        tracing::info!(?initialize_headers, %initialize_uri, "initialize from http server");
                    }
                    Ok(self.get_info())
                }
            }







        }



    };

    let result = [item, implementation.into()];
    proc_macro::TokenStream::from_iter(result)
}


pub fn impl_mcp_information_set(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let item_copy = item.clone();
    let ast = parse_macro_input!(item_copy as DeriveInput);
    let args = syn::parse_macro_input!(attr as MacroArgsEnvState);
    let scheme = args.scheme_type;
    let seed_type = args.seed_type;

    let implementation = {
        let ident = ast.ident.clone();

        let mcp_struct_name = syn::Ident::new(&format!("McpInfoSets{}", ident), proc_macro2::Span::call_site());

        quote!{
            #[automatically_derived]
            pub struct #mcp_struct_name{
                core: amfiteatr_core::agent::McpCoreInformationSets<#scheme, #ident, #seed_type>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#mcp_struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#mcp_struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }

            #[tool_router]
            #[automatically_derived]
            impl #mcp_struct_name {
                pub fn mcp_new(game_name: String, usage: String, initial_sets: std::collections::HashMap<<#scheme as amfiteatr_core::scheme::Scheme>::AgentId, #ident>) -> Self{
                    Self{
                        core: amfiteatr_core::agent::McpCoreInformationSets::new(initial_sets, game_name, usage),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router(),
                    }
                }
            }

            #[prompt_router]
            #[automatically_derived]
            impl #mcp_struct_name {

            }
        }
    };
    let result = [item, implementation.into()];
    proc_macro::TokenStream::from_iter(result)
}




pub fn impl_mcp_policy(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let item_copy = item.clone();

    let ast = parse_macro_input!(item_copy as ItemStruct);
    let args = syn::parse_macro_input!(attr as MacroArgsImplMcp);
    let scheme = args.scheme_type;
    let seed_type = args.seed_type;
    let target_type = args.target_type;

    let vis = ast.vis;
    let generics = ast.generics;
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let struct_name = ast.ident;
    let info_set_type = quote!{
        <#target_type as amfiteatr_core::agent::Policy<#scheme>>::InfoSetType
    };
    //let item = parse_macro_input!(item_copy as DeriveInput);
    /*let type_token = match item {
        //Item::Struct(=>)
    }


     */
    let output = {
        quote!{
            //::InfoSetType
            //<#target_type as amfiteatr_core::agent::Policy>
            #vis struct  #struct_name #generics{
                policy_wrap: amfiteatr_core::agent::McpCorePolicy<#scheme, <#target_type as amfiteatr_core::agent::Policy<#scheme>>::InfoSetType, #target_type>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }

            #[tool_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{
                pub fn mcp_new(policy: #target_type, policy_name: String, usage: String) -> Self{
                    Self{
                        policy_wrap: amfiteatr_core::agent::McpCorePolicy::new(policy, policy_name, usage),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router(),
                    }
                }
                pub async fn select_action(&self, parameters: rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqSelectAction<#scheme, #info_set_type>>)
                    -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {
                    self.policy_wrap.select_action(parameters).await
                }
            }

            #[prompt_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{

            }
        }
    };



    output.into()
    //let result: [proc_macro::TokenStream;1] = [output.into()];
    //proc_macro::TokenStream::from_iter(result)

}