use quote::quote;
use syn::{DeriveInput, parse_macro_input};

pub fn impl_mcp_env_state(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream{

    let item_copy = item.clone();
    let ast = parse_macro_input!(item_copy as DeriveInput);
    let scheme = parse_macro_input!(attr as syn::Ident);

    let implementation = {

        let ident = ast.ident.clone();

        let mcp_struct_name = syn::Ident::new(&format!("Mcp{}", ident), proc_macro2::Span::call_site());

        quote!{
            /// Generated by `mcp_env_state` macro.
            #[derive(Clone)]
            pub struct #mcp_struct_name {
                core: amfiteatr_core::env::McpCoreSequentialEnvironment<#scheme, #ident, ()>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#mcp_struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#mcp_struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }

            impl #mcp_struct_name{
                /// Creates new instance of structure
                pub fn mcp_new(initial_state: #ident) -> Self{
                    Self{
                        core: amfiteatr_core::env::McpCoreSequentialEnvironment::new(
                            initial_state
                        ),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router()
                    }
                }
            }

            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_router]
            impl #mcp_struct_name{

                fn _create_resource_text(&self, uri: &str, name: &str) -> rmcp::model::Resource {
                    rmcp::model::RawResource::new(uri, name.to_string()).no_annotation()
                }

                /// Generated by `mcp_env_state` macro.
                #[rmcp::tool(description = "Reset environment - set game in initial state")]
                async fn reset(&self) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {
                    self.core.reset(rmcp::handler::server::wrapper::Parameters(())).await
                }

                #[rmcp::tool(description = "Get updates for selected agent")]
                async fn get_updates(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {

                    self.core.get_updates(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await

                }

                #[rmcp::tool(description = "Get score of specific agent")]
                async fn get_score(
                    &self,
                   rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                )  -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{

                    self.core.get_score(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await
                }

                #[rmcp::tool(description = "Process action on environment and produce update messages")]
                async fn process_action(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentAction<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    self.core.process_action(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action})).await

                }

            }

            #[rmcp::prompt_router]
            impl #mcp_struct_name{
                #[rmcp::prompt(
                    name = "player_step_prompt",
                    meta = Meta(rmcp::object!({"meta_key": "meta_value"}))
                )]
                async fn player_step_prompt(
                    &self,
                    _ctx: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) ->  Result<rmcp::model::GetPromptResult, rmcp::ErrorData> {
                    self.core.player_step_prompt(_ctx).await
                }





            }


            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_handler(meta = Meta(rmcp::object!({"tool_meta_key": "tool_meta_value"})))]
            #[rmcp::prompt_handler(meta = Meta(rmcp::object!({"router_meta_key": "router_meta_value"})))]
            #[rmcp::task_handler]
            impl rmcp::ServerHandler for #mcp_struct_name{
                fn get_info(&self) -> rmcp::model::ServerInfo {

                    rmcp::model::ServerInfo::new(
                        rmcp::model::ServerCapabilities::builder()
                            .enable_tools()
                            .enable_prompts()
                            .enable_tasks()
                            .build()
                    )
                        .with_server_info(rmcp::model::Implementation::from_build_env())
                        .with_protocol_version(rmcp::model::ProtocolVersion::V_2024_11_05)
                        .with_instructions(format!("A game environment for game {} (controls game flow)", self.core.game_name()))
                }

                async fn initialize(
                    &self,
                    _request: rmcp::model::InitializeRequestParams,
                    context: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) -> Result<rmcp::model::InitializeResult, rmcp::ErrorData> {
                    if let Some(http_request_part) = context.extensions.get::<axum::http::request::Parts>() {
                        let initialize_headers = &http_request_part.headers;
                        let initialize_uri = &http_request_part.uri;
                        tracing::info!(?initialize_headers, %initialize_uri, "initialize from http server");
                    }
                    Ok(self.get_info())
                }
            }







        }



    };

    let result = [item, implementation.into()];
    proc_macro::TokenStream::from_iter(result)
}