use quote::quote;
use syn::{DeriveInput, parse_macro_input, Type, Token, parse_quote, Item, ItemStruct};
use syn::parse::Parse;


pub struct MacroArgsEnvState{
    scheme_type: Type,
    seed_type: Type,
}



impl Parse for MacroArgsEnvState {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut scheme_type = None;
        let mut seed_type = None;


        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let ty: Type = input.parse()?;

            match key.to_string().as_str() {

                "scheme" => scheme_type = Some(ty),
                "seed_type" => seed_type = Some(ty),
                _ => return Err(syn::Error::new(key.span(), "unknown argument")),
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(MacroArgsEnvState {
            scheme_type: scheme_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing scheme")
            })?,
            seed_type: seed_type.unwrap_or_else(|| syn::parse_quote!(())),
        })
    }
}


pub struct MacroArgsImplMcp{
    target_type: Type,
    scheme_type: Type,
    seed_type: Type,
}
impl Parse for MacroArgsImplMcp {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut scheme_type = None;
        let mut seed_type = None;
        let mut target_type = None;

        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let ty: Type = input.parse()?;

            match key.to_string().as_str() {
                "target" => target_type = Some(ty),
                "scheme" => scheme_type = Some(ty),
                "seed_type" => seed_type = Some(ty),
                _ => return Err(syn::Error::new(key.span(), "unknown argument")),
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(MacroArgsImplMcp {
            scheme_type: scheme_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing scheme")
            })?,
            seed_type: seed_type.unwrap_or_else(|| syn::parse_quote!(())),
            target_type: target_type.ok_or_else(|| {
                syn::Error::new(proc_macro2::Span::call_site(), "missing target")
            })?,

        })
    }
}

pub fn impl_mcp_env_state(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream{


    let item_copy = item.clone();
    let ast = parse_macro_input!(item_copy as DeriveInput);
    let ident = ast.ident.clone();
    //let scheme = parse_macro_input!(attr as syn::Ident);
    let args = syn::parse_macro_input!(attr as MacroArgsImplMcp);
    let scheme = args.scheme_type;
    let seed_type = args.seed_type;
    let target_type = args.target_type;
    let vis = ast.vis;
    let generics = ast.generics;
    let struct_name = ast.ident;
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    let output = {



        //let mcp_struct_name = syn::Ident::new(&format!("Mcp{}", ident), proc_macro2::Span::call_site());

        quote!{
            /// Generated by `mcp_env_state` macro.
            #vis struct #struct_name #generics {
                core: amfiteatr_core::env::McpCoreSequentialEnvironment<#scheme, #target_type, ()>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }


            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{
                /// Creates new instance of structure
                pub fn mcp_new(initial_state: #target_type) -> Self{
                    Self{
                        core: amfiteatr_core::env::McpCoreSequentialEnvironment::new(
                            initial_state
                        ),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router()
                    }
                }
            }


            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_router]
            impl #impl_generics #struct_name #ty_generics #where_clause{

                fn _create_resource_text(&self, uri: &str, name: &str) -> rmcp::model::Resource {
                    rmcp::model::RawResource::new(uri, name.to_string()).no_annotation()
                }

                /// Generated by `mcp_env_state` macro.
                #[rmcp::tool(description = "Reset environment - set game in initial state")]
                async fn reset(&self) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {
                    self.core.reset(rmcp::handler::server::wrapper::Parameters(#seed_type)).await
                }

                #[rmcp::tool(description = "Get updates for selected agent")]
                async fn get_updates(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {

                    self.core.get_updates(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await

                }


                #[rmcp::tool(description = "Get score of specific agent")]
                async fn get_score(
                    &self,
                   rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentId<#scheme>>
                )  -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{

                    self.core.get_score(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentId{agent_id})).await
                }


                #[rmcp::tool(description = "Process action on environment and produce update messages")]
                async fn process_action(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqArgAgentAction<#scheme>>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    self.core.process_action(rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqArgAgentAction{agent_id, action})).await

                }



            }


            #[rmcp::prompt_router]
            impl #impl_generics #struct_name #ty_generics #where_clause{
                #[rmcp::prompt(
                    name = "player_step_prompt",
                    meta = Meta(rmcp::object!({"meta_key": "meta_value"}))
                )]
                async fn player_step_prompt(
                    &self,
                    _ctx: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) ->  Result<rmcp::model::GetPromptResult, rmcp::ErrorData> {
                    self.core.player_step_prompt(_ctx).await
                }





            }


            /// Generated by `mcp_env_state` macro.
            #[rmcp::tool_handler(meta = Meta(rmcp::object!({"tool_meta_key": "tool_meta_value"})))]
            #[rmcp::prompt_handler(meta = Meta(rmcp::object!({"router_meta_key": "router_meta_value"})))]
            //#[rmcp::task_handler]
            impl #impl_generics rmcp::ServerHandler for #struct_name #ty_generics #where_clause{
                fn get_info(&self) -> rmcp::model::ServerInfo {

                    rmcp::model::ServerInfo::new(
                        rmcp::model::ServerCapabilities::builder()
                            .enable_tools()
                            .enable_prompts()
                            //.enable_tasks()
                            .build()
                    )
                        .with_server_info(rmcp::model::Implementation::from_build_env())
                        .with_protocol_version(rmcp::model::ProtocolVersion::V_2024_11_05)
                        .with_instructions(format!("A game environment for game {} (controls game flow)", self.core.game_name()))
                }

                async fn initialize(
                    &self,
                    _request: rmcp::model::InitializeRequestParams,
                    context: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) -> Result<rmcp::model::InitializeResult, rmcp::ErrorData> {
                    if let Some(http_request_part) = context.extensions.get::<axum::http::request::Parts>() {
                        let initialize_headers = &http_request_part.headers;
                        let initialize_uri = &http_request_part.uri;
                        tracing::info!(?initialize_headers, %initialize_uri, "initialize from http server");
                    }
                    Ok(self.get_info())
                }
            }







        }



    };

    output.into()
    //let result = [implementation.into()];
    //proc_macro::TokenStream::from_iter(result)
}


pub fn impl_mcp_information_set(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let item_copy = item.clone();
    let ast = parse_macro_input!(item_copy as DeriveInput);
    let ident = ast.ident.clone();
    let args = syn::parse_macro_input!(attr as MacroArgsImplMcp);
    let scheme = args.scheme_type;
    let seed_type = args.seed_type;
    let target_type = args.target_type;
    let vis = ast.vis;
    let generics = ast.generics;
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let struct_name = ast.ident;

    let output = {


        //let mcp_struct_name = syn::Ident::new(&format!("McpInfoSets{}", ident), proc_macro2::Span::call_site());

        quote!{
            #[automatically_derived]
            #vis struct  #struct_name #generics{
                core: amfiteatr_core::agent::McpCoreInformationSets<#scheme, #target_type, #seed_type>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }


            #[rmcp::tool_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{
                pub fn mcp_new(game_name: String, usage: String, initial_sets: std::collections::HashMap<<#scheme as amfiteatr_core::scheme::Scheme>::AgentId, #target_type>) -> Self{
                    Self{
                        core: amfiteatr_core::agent::McpCoreInformationSets::new(initial_sets, game_name, usage),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router(),
                    }
                }
                #[tool(description = "Reset all information sets - set them to initial values - for all players")]
                pub async fn reset_all_information_sets(
                    &self,
                    rmcp::handler::server::wrapper::Parameters(initial_info_set): rmcp::handler::server::wrapper::Parameters<#seed_type>
                ) -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    match self.core.reset_information_sets(initial_info_set).await{
                        Ok(_) => Ok(rmcp::model::CallToolResult::success(vec![])),
                        Err(e) => Err(rmcp::ErrorData::internal_error(
                            format!("Failed to reset information sets: ({e})"),
                            None
                        ))
                    }
                }
            }

            #[rmcp::prompt_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{

            }


            #[rmcp::tool_handler(meta = Meta(rmcp::object!({"tool_meta_key": "tool_meta_value"})))]
            #[rmcp::prompt_handler(meta = Meta(rmcp::object!({"router_meta_key": "router_meta_value"})))]
            //#[rmcp::task_handler]
            #[automatically_derived]
            impl #impl_generics rmcp::ServerHandler for #struct_name #ty_generics #where_clause{
                fn get_info(&self) -> rmcp::model::ServerInfo {

                    rmcp::model::ServerInfo::new(
                        rmcp::model::ServerCapabilities::builder()
                            .enable_tools()
                            .enable_prompts()
                            .enable_tasks()
                            .build()
                    )
                        .with_server_info(rmcp::model::Implementation::from_build_env())
                        .with_protocol_version(rmcp::model::ProtocolVersion::V_2024_11_05)
                        .with_instructions("Informatin Sets  - holds agents'/players' knowledge of game state, and perform it updates based on provided observations")
                }

                async fn initialize(
                    &self,
                    _request: rmcp::model::InitializeRequestParams,
                    context: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) -> Result<rmcp::model::InitializeResult, rmcp::ErrorData> {
                    if let Some(http_request_part) = context.extensions.get::<axum::http::request::Parts>() {
                        let initialize_headers = &http_request_part.headers;
                        let initialize_uri = &http_request_part.uri;
                        tracing::info!(?initialize_headers, %initialize_uri, "initialize from http server");
                    }
                    Ok(self.get_info())
                }
            }
        }
    };
    //let result = [item, implementation.into()];
    //proc_macro::TokenStream::from_iter(result)

    output.into()
}




pub fn impl_mcp_policy(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let item_copy = item.clone();

    let ast = parse_macro_input!(item_copy as ItemStruct);
    let args = syn::parse_macro_input!(attr as MacroArgsImplMcp);
    let scheme = args.scheme_type;
    //let seed_type = args.seed_type;
    let target_type = args.target_type;

    let vis = ast.vis;
    let generics = ast.generics;
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let struct_name = ast.ident;
    let info_set_type = quote!{
        <#target_type as amfiteatr_core::agent::Policy<#scheme>>::InfoSetType
    };
    //let item = parse_macro_input!(item_copy as DeriveInput);
    /*let type_token = match item {
        //Item::Struct(=>)
    }


     */
    let output = {
        quote!{
            //::InfoSetType
            //<#target_type as amfiteatr_core::agent::Policy>
            #vis struct  #struct_name #generics{
                policy_wrap: amfiteatr_core::agent::McpCorePolicy<#scheme, <#target_type as amfiteatr_core::agent::Policy<#scheme>>::InfoSetType, #target_type>,
                tool_router: rmcp::handler::server::router::tool::ToolRouter<#struct_name>,
                prompt_router: rmcp::handler::server::router::prompt::PromptRouter<#struct_name>,
                processor: std::sync::Arc<tokio::sync::Mutex<rmcp::task_manager::OperationProcessor>>,
            }

            #[rmcp::tool_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{
                pub fn mcp_new(policy: #target_type, policy_name: String, usage: String) -> Self{
                    Self{
                        policy_wrap: amfiteatr_core::agent::McpCorePolicy::new(policy, policy_name, usage),
                        tool_router: Self::tool_router(),
                        processor: std::sync::Arc::new(tokio::sync::Mutex::new(rmcp::task_manager::OperationProcessor::new())),
                        prompt_router: Self::prompt_router(),
                    }
                }
                #[rmcp::tool(description = "Selects action based on provided information set (a portion of state viewed by player/agent)")]
                pub async fn select_action(&self, rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqSelectAction{information_set, ..}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqSelectAction<#scheme, #info_set_type>>)
                    -> Result<rmcp::model::CallToolResult, rmcp::ErrorData>
                {
                    match self.policy_wrap.select_action(&information_set).await {

                        Ok(action) => Ok(rmcp::model::CallToolResult::success(vec![rmcp::model::Content::json(action)?])),
                        Err(e) => Err(rmcp::ErrorData::internal_error(
                            format!("Failed to resolve action ({e})"),
                            Some(serde_json::to_value(&information_set).map_err(|e|{
                                rmcp::ErrorData::internal_error(
                                    format!("Failed to resolve action ({e}) and to serialize information set: {information_set:?}."),
                                    None
                                )
                            })?))),
                    }
                }

                #[rmcp::tool(description = "Call this tool on start of the episode, it does things specific to policy on the start of the game - it is defined by specific policy and usually is some internal adjustment.")]
                pub async fn call_on_episode_start(&self) ->  Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    match self.policy_wrap.call_on_episode_start().await{
                        Ok(_) => Ok(rmcp::model::CallToolResult::success(vec![])),
                        Err(e) => Err(rmcp::ErrorData::internal_error(
                            format!("Failed to policy preparation on beginning of the episode ({e})"),
                            None
                        ))
                    }
                }

                #[rmcp::tool(description = "Call this tool on start of the episode, it does things specific to policy on the end of the game - it is defined by specific policy and usually is some internal adjustment.")]
                pub async fn call_on_episode_finish(&self, rmcp::handler::server::wrapper::Parameters(amfiteatr_core::util::mcp::McpReqReward{reward}): rmcp::handler::server::wrapper::Parameters<amfiteatr_core::util::mcp::McpReqReward<#scheme>>) ->  Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    match self.policy_wrap.call_on_episode_finish(reward).await{
                        Ok(_) => Ok(rmcp::model::CallToolResult::success(vec![])),
                        Err(e) => Err(rmcp::ErrorData::internal_error(
                            format!("Failed to policy preparation on beginning of the episode ({e})"),
                            None
                        ))
                    }
                }

                #[rmcp::tool(description = "Call this between learning epochs, it does things specific to policy on the end of the game - it is defined by specific policy and usually is some internal logic to prepare for new learning epoch.")]
                pub async fn call_between_epochs(&self) ->  Result<rmcp::model::CallToolResult, rmcp::ErrorData>{
                    match self.policy_wrap.call_on_episode_start().await{
                        Ok(_) => Ok(rmcp::model::CallToolResult::success(vec![])),
                        Err(e) => Err(rmcp::ErrorData::internal_error(
                            format!("Failed to policy preparation on beginning of the episode ({e})"),
                            None
                        ))
                    }
                }


            }

            #[rmcp::prompt_router]
            #[automatically_derived]
            impl #impl_generics #struct_name #ty_generics #where_clause{

            }

            #[rmcp::tool_handler(meta = Meta(rmcp::object!({"tool_meta_key": "tool_meta_value"})))]
            #[rmcp::prompt_handler(meta = Meta(rmcp::object!({"router_meta_key": "router_meta_value"})))]
            //#[rmcp::task_handler]
            #[automatically_derived]
            impl #impl_generics rmcp::ServerHandler for #struct_name #ty_generics #where_clause{
                fn get_info(&self) -> rmcp::model::ServerInfo {

                    rmcp::model::ServerInfo::new(
                        rmcp::model::ServerCapabilities::builder()
                            .enable_tools()
                            .enable_prompts()
                            .enable_tasks()
                            .build()
                    )
                        .with_server_info(rmcp::model::Implementation::from_build_env())
                        .with_protocol_version(rmcp::model::ProtocolVersion::V_2024_11_05)
                        .with_instructions(format!("Policy  {} - advices player (or agent) what to do in current situation", self.policy_wrap.name()))
                }

                async fn initialize(
                    &self,
                    _request: rmcp::model::InitializeRequestParams,
                    context: rmcp::service::RequestContext<rmcp::RoleServer>,
                ) -> Result<rmcp::model::InitializeResult, rmcp::ErrorData> {
                    if let Some(http_request_part) = context.extensions.get::<axum::http::request::Parts>() {
                        let initialize_headers = &http_request_part.headers;
                        let initialize_uri = &http_request_part.uri;
                        tracing::info!(?initialize_headers, %initialize_uri, "initialize from http server");
                    }
                    Ok(self.get_info())
                }
            }
        }
    };



    output.into()
    //let result: [proc_macro::TokenStream;1] = [output.into()];
    //proc_macro::TokenStream::from_iter(result)

}